"""Run batch inference with the final ConvNeXt-Tiny phase-state classifier.

The model follows the class encoding used in final_evaluation.py:

    phase   = 0
    uniform = 1

The sigmoid-transformed model output is interpreted as P(uniform). The fixed
decision threshold selected from grouped out-of-fold predictions is 0.21:

    P(uniform) > 0.21  -> uniform
    P(uniform) <= 0.21 -> phase

The input images should be the standardized PNG images generated by
preprocess_images.py. Raw microscope TIFF files should be preprocessed before
running this script.

Example
-------
python predict.py /path/to/processed_png /path/to/FINAL_MODEL_convnext_tiny.pth results/prediction/
"""

from __future__ import annotations

import argparse
import json
import logging
from pathlib import Path
from typing import Sequence

import albumentations as A
import cv2
import numpy as np
import pandas as pd
import timm
import torch
from albumentations.pytorch import ToTensorV2
from torch import nn
from torch.utils.data import DataLoader, Dataset


LOGGER = logging.getLogger(__name__)

CLASS_NAMES = ("phase", "uniform")
CLASS_TO_INDEX = {"phase": 0, "uniform": 1}
IMAGE_SUFFIXES = {".png"}


class InferenceImageDataset(Dataset):
    """Read image files and apply the final-evaluation preprocessing transform."""

    def __init__(self, image_paths: Sequence[Path], root_dir: Path, transform: A.Compose) -> None:
        self.image_paths = list(image_paths)
        self.root_dir = root_dir
        self.transform = transform

    def __len__(self) -> int:
        return len(self.image_paths)

    def __getitem__(self, index: int) -> tuple[torch.Tensor, str]:
        image_path = self.image_paths[index]
        image_gray = cv2.imread(
            str(image_path),
            cv2.IMREAD_GRAYSCALE,
        )

        if image_gray is None:
            raise OSError(
                f"OpenCV could not read image: {image_path}"
            )

        image_rgb = cv2.cvtColor(
            image_gray,
            cv2.COLOR_GRAY2RGB,
        )
        image = self.transform(image=image_rgb)["image"]
        relative_path = str(image_path.relative_to(self.root_dir))
        return image, relative_path


def set_seed(seed: int) -> None:
    """Control pseudorandomness for deterministic inference behavior."""
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def build_transform(image_size: int) -> A.Compose:
    """Use the same deterministic image transform as final_evaluation.py."""
    return A.Compose(
        [
            A.Resize(image_size, image_size),
            A.Normalize(
                mean=(0.485, 0.456, 0.406),
                std=(0.229, 0.224, 0.225),
            ),
            ToTensorV2(),
        ]
    )


def collect_images(input_path: Path, recursive: bool) -> tuple[list[Path], Path]:
    """Collect image paths from one image file or from a directory."""
    input_path = input_path.expanduser().resolve()
    if not input_path.exists():
        raise FileNotFoundError(f"Input path does not exist: {input_path}")

    if input_path.is_file():
        if input_path.suffix.lower() not in IMAGE_SUFFIXES:
            raise ValueError(f"Unsupported image file extension: {input_path.suffix}")
        return [input_path], input_path.parent

    if not input_path.is_dir():
        raise ValueError(f"Input path is neither a file nor a directory: {input_path}")

    iterator = input_path.rglob("*") if recursive else input_path.glob("*")
    image_paths = sorted(
        path.resolve()
        for path in iterator
        if path.is_file() and path.suffix.lower() in IMAGE_SUFFIXES
    )
    if not image_paths:
        raise FileNotFoundError(f"No supported image files were found in: {input_path}")
    return image_paths, input_path


def load_model(model_path: Path, model_name: str, device: torch.device) -> nn.Module:
    """Load the state_dict saved by final_evaluation.py."""
    model_path = model_path.expanduser().resolve()
    if not model_path.is_file():
        raise FileNotFoundError(f"Model checkpoint does not exist: {model_path}")

    model = timm.create_model(model_name, pretrained=False, num_classes=1)
    state_dict = torch.load(model_path, map_location="cpu")
    if isinstance(state_dict, dict) and "state_dict" in state_dict:
        state_dict = state_dict["state_dict"]
    if not isinstance(state_dict, dict):
        raise TypeError("The checkpoint must be a state_dict or contain a 'state_dict' entry.")

    state_dict = {
        key.replace("module.", "", 1) if key.startswith("module.") else key: value
        for key, value in state_dict.items()
    }
    model.load_state_dict(state_dict, strict=True)
    model.to(device)
    model.eval()
    return model


def run_prediction(
    model: nn.Module,
    loader: DataLoader,
    device: torch.device,
    threshold: float,
) -> pd.DataFrame:
    """Return one prediction row per image."""
    records: list[dict[str, object]] = []

    with torch.no_grad():
        for images, relative_paths in loader:
            images = images.to(device)
            probabilities = torch.sigmoid(model(images)).cpu().numpy().ravel()
            predicted_indices = (probabilities > threshold).astype(int)

            for relative_path, probability_uniform, predicted_index in zip(
                relative_paths, probabilities, predicted_indices, strict=True
            ):
                probability_uniform = float(probability_uniform)
                probability_phase = 1.0 - probability_uniform
                predicted_class = CLASS_NAMES[int(predicted_index)]
                records.append(
                    {
                        "relative_path": relative_path,
                        "probability_uniform": probability_uniform,
                        "probability_phase": probability_phase,
                        "threshold": float(threshold),
                        "predicted_index": int(predicted_index),
                        "predicted_class": predicted_class,
                    }
                )

    return pd.DataFrame.from_records(records)


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    """Parse input, checkpoint, output, and fixed inference settings."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("input_path", type=Path, help="Standardized image file or directory.")
    parser.add_argument("model_path", type=Path, help="Final ConvNeXt-Tiny checkpoint.")
    parser.add_argument("output_dir", type=Path, help="Directory for prediction outputs.")
    parser.add_argument("--model", default="convnext_tiny", help="timm model identifier.")
    parser.add_argument("--threshold", type=float, default=0.21, help="Fixed threshold applied to P(uniform).")
    parser.add_argument("--batch-size", type=int, default=32, help="Inference batch size.")
    parser.add_argument("--image-size", type=int, default=224, help="Model input size.")
    parser.add_argument("--workers", type=int, default=2, help="Number of DataLoader workers.")
    parser.add_argument("--recursive", action="store_true", help="Search input subdirectories recursively.")
    parser.add_argument("--seed", type=int, default=42, help="Random seed.")
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    """Run inference and save predictions plus run metadata."""
    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
    args = parse_args(argv)

    if not 0.0 < args.threshold < 1.0:
        raise ValueError("The classification threshold must be in (0, 1).")
    if min(args.batch_size, args.image_size) <= 0 or args.workers < 0:
        raise ValueError("Batch size and image size must be positive; workers cannot be negative.")

    set_seed(args.seed)
    output_dir = args.output_dir.expanduser().resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    image_paths, root_dir = collect_images(args.input_path, recursive=args.recursive)
    transform = build_transform(args.image_size)
    dataset = InferenceImageDataset(image_paths, root_dir, transform)
    loader = DataLoader(
        dataset,
        batch_size=args.batch_size,
        shuffle=False,
        num_workers=args.workers,
        pin_memory=torch.cuda.is_available(),
        persistent_workers=args.workers > 0,
    )

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = load_model(args.model_path, args.model, device)
    predictions = run_prediction(model, loader, device, args.threshold)

    prediction_path = output_dir / "predictions.csv"
    predictions.to_csv(prediction_path, index=False)

    metadata = {
        "model": args.model,
        "model_path": str(args.model_path.expanduser().resolve()),
        "input_path": str(args.input_path.expanduser().resolve()),
        "output_dir": str(output_dir),
        "class_mapping": CLASS_TO_INDEX,
        "positive_probability": "P(uniform)",
        "threshold": args.threshold,
        "image_size": args.image_size,
        "batch_size": args.batch_size,
        "seed": args.seed,
        "device": str(device),
        "number_of_images": int(len(predictions)),
        "prediction_file": prediction_path.name,
    }
    (output_dir / "prediction_metadata.json").write_text(
        json.dumps(metadata, indent=2), encoding="utf-8"
    )

    class_counts = predictions["predicted_class"].value_counts().to_dict()
    LOGGER.info("Saved predictions to %s", prediction_path)
    LOGGER.info("Predicted class counts: %s", class_counts)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
